
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
`timescale 1ns/1ps
module DE0_CV(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_1
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

logic [13:0] r_LPF_threshold;
assign r_LPF_threshold = 14'd200;


//=======================================================
//  Structural coding
//=======================================================

RS232 t1(
	.rst(RESET_N),
	.clk(CLOCK_50),
	.r_LPF_threshold(r_LPF_threshold),
	.rx(GPIO_0[2]),
	.tx(GPIO_0[4])
);

/*logic locked;
logic clk_100;
pll s1(
	.refclk(CLOCK_50),
	.rst(~RESET_N),
	.outclk_0(clk_100),
	.outclk_1(),
	.locked(locked)
	);

logic [15:0]data;
logic mosi;
logic ssn;
logic sclk;
spi_rx s2(
	.clk(clk_100),
	.mosi(GPIO_0[0]),
	.ssn(GPIO_0[2]),
	.sclk(GPIO_0[1]),
	.rst(RESET_N),
	.miso(GPIO_0[3]),
	.address(),
	.data(),
	.read_en(),
	.write_en(),
	.tx_req()
	);
assign LEDR = data[9:0];

Low_Pass_Filter a1(
	.sig_filter(mosi),	
	.signal(GPIO_0[0]),	
	.r_LPF_threshold(),
	.clk(CLOCK_50), 
	.reset(RESET_N)
);
Low_Pass_Filter a2(
	.sig_filter(ssn),	
	.signal(GPIO_0[2]),	
	.r_LPF_threshold(),
	.clk(CLOCK_50), 
	.reset(RESET_N)
);
Low_Pass_Filter a3(
	.sig_filter(sclk),	
	.signal(GPIO_0[1]),	
	.r_LPF_threshold(),
	.clk(CLOCK_50), 
	.reset(RESET_N)
);*/
endmodule
